### PR TITLE
Fixed #258 POM / PluginManagement Improvements

### LINKED ISSUE #258: POM / PluginManagement Improvements
Upgrade maven-plugin-plugin to 3.4
Upgrade maven-invoker-plugin to 2.0.0 and cleaned up pom accordingly.
Upgrade maven-source-plugin from 2.2.1 to 2.4 added config to replace configuration of the super pom to prevent forks of the life cycle.
Upgrade doxia-module-markdown from 1.4 to 1.6
Upgrade maven-shade-plugin from 2.3 to 2.4.1
Upgrade maven-jar-plugin from 2.4 to 2.6
Upgrade maven-assembly-plugin from 2.5.3 to 2.5.5
Correct usage of maven-plugin-annotations (scope=provided)

### PR DESCRIPTION
**Pull request by khmarbaise**
- Upgrade maven-plugin-plugin to 3.4
- Upgrade maven-invoker-plugin to 2.0.0 and cleaned up pom accordingly.
- Upgrade maven-source-plugin from 2.2.1 to 2.4 added config to replace
- configuration of the super pom to prevent forks of the life cycle.
- Upgrade doxia-module-markdown from 1.4 to 1.6
- Upgrade maven-shade-plugin from 2.3 to 2.4.1
- Upgrade maven-jar-plugin from 2.4 to 2.6
- Upgrade maven-assembly-plugin from 2.5.3 to 2.5.5
- Correct usage of maven-plugin-annotations (scope=provided)

### CODE REVIEW

**Comment by DirkMahler** [comment]
I've never felt so well about POM files ;-) Thanks!

**Comment by khmarbaise** [comment]
Ah...you were too fast, cause i have squashed the changes together...

**Comment by DirkMahler** [comment]
Sorry, the changes looked well and it was just one click away to merge...

**Comment by khmarbaise** [comment]
Sure no problem...but the change history does not look so beautiful ;-(...

**Comment by obfischer** [comment]
Can we close this now?

**Comment by khmarbaise** [comment]
Sure...

**Comment by obfischer** [comment]
Patch applied. Thx.

**Pull request merged**
