### PR TITLE
- adapt SONAR changes from 3.7.4 to 5.0 API

### PR DESCRIPTION
**Pull request by rzozmann**
Fix SONAR integration as in https://github.com/buschmais/jqassistant/issues/338 mentioned. Some more words:
- SONAR has had major changes in API since 3.7.4. These cannot be handled as compatible between the several api version. I increased also other plugin versions...
- The JavaResourceResolver still contains code possible not working, because the JavaFile replacement File, does not the same! Here we need more time to inspect. The JavaResourceResolverTest is currently @Ignore'd.
- I replaced also some other decpreactions by recommended alternatives.

### CODE REVIEW

**Comment by obfischer** [comment]
Hi @rzozmann, the Sonar plugin has now its own repository at https://github.com/buschmais/jqassistant-sonar-plugin. At the moment it is only a fork of the jQAssistant repository. Our plan is to have a more modulare structure to iterate faster. Therefor we will divide the core framework and the plugins. Can you try to apply the patch on this repository or provide us a patch?

BTW, is our patch based on the 1.1 or master branch?

**Comment by DirkMahler** [comment]
@obfischer would be good to have it for 1.1, we need to discuss how to transfer it to the separated master repositories.

**Comment by DirkMahler** [comment]
@rzozmann We're going to merge the PR - but we need to align it with some structural changes in the master (the SonarQube plugin will be moved to a separate repository). So asking you for some patience...

**Comment by rzozmann** [comment]
I have locally more changes while playing with the requirements as explained in https://github.com/buschmais/jqassistant/issues/338. Now there are some refactorings affecting also the maven modules.
Several of these changes are only useful if i found a final solution for some of my ponderings.

**It is possible to delay the merge by some days (i have to find a solution in the next days or to give up)?** Then i can make the decision to revert parts of my work, but to keep some other changes related to current state in 1.1.1 of SONAR integration.

Perceptions related to my work and the SONAR integration in general are:
- The JQAssistantSensor is slightly refactored, there is now also a basic configuration (disabling jqassistant sensor for sonar runs, custom report file path)
- Some unit tests are affected and to be adapted
- The original sonar plugin has a size of 70 MB, it's containing all other jqassistant jar's, but required are only 'report' and 'java' for the pure Sonar-Sensor functionality.
- All other jqassistant plugins are only required for hosting of embedded jqassistant-rules mapped into sonar rules (the neo4j jar's are useless here). The huge plugin jar is downloaded to clients for sonar runs, so we should reduce the size for that. Separating into more plugins (one for sensor, one for importing rules into sonar,...) may help...
- But the real challenge for me is the fact, that violations must be related to a rule and SONAR has no import/upload capability for rules (there is only a customizable profile import). Because i think about a improvement of the jqassistant-maven-plugin to upload local custom rules (in /jqassistant dir) as rules into SonarQ to make the rules available before the sonar runner is started.

That's as current state to give you the opportunity to decide.
Regards
Ralf

**Comment by DirkMahler** [comment]
All mentioned points are valid - the last one was that what I described as technical gap between jQA and SonarQube.
If you found a solution for efficiently propagating the rules to SonarQube I'd be very happy. The idea of integrating that into Maven (or the command line utility) sounds good.
So I'd propose that we take the PR for 1.1 and care about the merge stuff later. There will be no development on the SonarQube plugin in other branches/repos right now.

**Comment by DirkMahler** [comment]
Remarks:
- I'd like to coordinate with you the Maven part before any development starts.
- Merging that change into 1.1 means that we current SonarQube users need to upgrade to 5.x. Not really good for a minor release but I think that currently nobody is really using the plugin right now.

**Pull request merged**
