### PR TITLE
Various improvements for the YAML plugin

### PR DESCRIPTION
**Pull request by obfischer**
This pull request contains some code cleanup and an important note in the documentation that the YAML scanner does not support all valid YAML documents.

### CODE REVIEW

**Comment by DirkMahler** [comment]
Thanks!

**Comment by DirkMahler** [comment]
@obfischer After merging YAMLFileScannerPluginValidFileSetIT fails on file ""/probes/yamlspec/1.1/sec-2.2-example-2.11-mapping-betweend-sequences.yaml" which has been activated by this PR. Can you verify this?

**Comment by obfischer** [comment]
I can not reproduce it. Can you add here the full error message of the failing test?

**Comment by DirkMahler** [comment]
```
java.lang.IllegalStateException: Unexpected problem while scanning: item='/opt/jenkins/var/jobs/jqassistant-integration/workspace/plugin/yaml/target/test-classes/probes/yamlspec/1.1/sec-2.2-example-2.11-mapping-betweend-sequences.yaml', path='/opt/jenkins/var/jobs/jqassistant-integration/workspace/plugin/yaml/target/test-classes/probes/yamlspec/1.1/sec-2.2-example-2.11-mapping-betweend-sequences.yaml', scope='null', pipeline='[com.buschmais.jqassistant.plugin.common.impl.scanner.FileScannerPlugin@1e286604]'.
	at com.buschmais.jqassistant.plugin.yaml.impl.scanner.YAMLEmitter.unsupportedYAMLStructure(YAMLEmitter.java:289)
	at com.buschmais.jqassistant.plugin.yaml.impl.scanner.YAMLEmitter.handleSequenceEnd(YAMLEmitter.java:118)
	at com.buschmais.jqassistant.plugin.yaml.impl.scanner.YAMLEmitter.emit(YAMLEmitter.java:63)
	at org.yaml.snakeyaml.serializer.Serializer.serializeNode(Serializer.java:193)
	at org.yaml.snakeyaml.serializer.Serializer.serializeNode(Serializer.java:205)
	at org.yaml.snakeyaml.serializer.Serializer.serialize(Serializer.java:112)
	at com.buschmais.jqassistant.plugin.yaml.impl.scanner.YAMLFileScannerPlugin.scan(YAMLFileScannerPlugin.java:65)
	at com.buschmais.jqassistant.plugin.yaml.impl.scanner.YAMLFileScannerPlugin.scan(YAMLFileScannerPlugin.java:27)
	at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:77)
	at com.buschmais.jqassistant.plugin.common.impl.scanner.FileScannerPlugin.scan(FileScannerPlugin.java:50)
	at com.buschmais.jqassistant.plugin.common.impl.scanner.FileScannerPlugin.scan(FileScannerPlugin.java:20)
	at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:77)
	at com.buschmais.jqassistant.plugin.yaml.impl.scanner.YAMLFileScannerPluginValidFileSetIT.canLoadYAMLFile(YAMLFileScannerPluginValidFileSetIT.java:71)
```

Note: Exception handling has changed in origin/master such that any runtime exception thrown by a scanner plugin now aborts scanning. IOExceptions may be thrown to indicate that a problem was detected while scanning an item, in this case the scanner will proceed.

**Comment by obfischer** [comment]
Ok, I can reproduce this bug. I will try to fix it today.

**Comment by obfischer** [comment]
I fixed the test case. I will create a new pull request now.

**Pull request merged**
